//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copiosis_Application.DB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int productID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int gateway { get; set; }
        public int itemClass { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public int ownerID { get; set; }
        public System.Guid guid { get; set; }
        public string type { get; set; }
    
        public virtual itemClass itemClass1 { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual user user { get; set; }
    }
}
