//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copiosis_Application.DB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.transactions = new HashSet<transaction>();
            this.producerTransactions = new HashSet<transaction>();
            this.consumerTransactions = new HashSet<transaction>();
            this.products = new HashSet<product>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int status { get; set; }
        public Nullable<double> nbr { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public int locationID { get; set; }
        public Nullable<System.DateTime> prevLastLogin { get; set; }
        public int vendorCode { get; set; }
    
        public virtual location location { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual ICollection<transaction> producerTransactions { get; set; }
        public virtual ICollection<transaction> consumerTransactions { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
